In [31]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,2],[3,4]])
B = np.array([[5,6,7],[7,80,9],[9,10,22]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[ 5  6  7]
 [ 7 80  9]
 [ 9 10 22]]


In [32]:
# determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)
# inverse of A
inv_A = np.linalg.inv(A)
print("\nInverse of Matrix A:\n", inv_A)

# determinant of B
det_B = np.linalg.det(B)
print("\nDeterminant of Matrix B:", det_B)
# inverse of B
inv_B = np.linalg.inv(B)
print("\nInverse of Matrix B:\n", inv_B)


Determinant of Matrix A: -2.0000000000000004

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix B: 3362.0000000000014

Inverse of Matrix B:
 [[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]


In [33]:
det_A = A[0,0]*A[1,1] - A[0,1]*A[1,0]
print("Determinant of Matrix A:", det_A)

det_B = B[0,0]*B[1,1]*B[2,2] + B[0,1]*B[1,2]*B[2,0] + B[0,2]*B[1,0]*B[2,1] - B[0,0]*B[1,2]*B[2,1] - B[0,1]*B[1,0]*B[2,2] - B[0,2]*B[1,1]*B[2,0]
print(f"Determinant of Matrix B: {det_B}")
print(f'{B[0,0]*B[1,1]*B[2,2]=}\n{B[0,1]*B[1,2]*B[2,0]=}\n{B[0,2]*B[1,0]*B[2,1]=}\n{B[0,0]*B[1,2]*B[2,1]=}\n{B[0,1]*B[1,0]*B[2,2]=}\n{B[0,2]*B[1,1]*B[2,0]=}')

Determinant of Matrix A: -2
Determinant of Matrix B: 3362
B[0,0]*B[1,1]*B[2,2]=8800
B[0,1]*B[1,2]*B[2,0]=486
B[0,2]*B[1,0]*B[2,1]=490
B[0,0]*B[1,2]*B[2,1]=450
B[0,1]*B[1,0]*B[2,2]=924
B[0,2]*B[1,1]*B[2,0]=5040


Calculating the determinant of a matrix using the formulae (where $A_{\backslash i,\backslash j}$ means the matrix with row i and column j removed):

$$ \begin{align}
|A| &= \sum_{i=1}^{n} (-1)^{i+j} a_{ij} |A_{\backslash i,\backslash j}| \\
    &= \sum_{j=1}^{n} (-1)^{i+j} a_{ij} |A_{\backslash i,\backslash j}|
\end{align} $$

In [37]:
def determinant(mat):
    n = len(mat)
    if n == 1:
        return mat[0][0]
    else:
        det = 0
        i = 0
        j = 0
        for i in range(n): # this works whether on each row (i) or each column (j)
            sub_mat = np.delete(mat, i, axis=0)       # delete the i-th row
            sub_mat = np.delete(sub_mat, j, axis=1)   # delete the j-th column
            sign = (-1)**(i+j)
            det += sign * mat[i][j] * determinant(sub_mat)
        return det
    
print("Determinant of Matrix A:", determinant(A))
print("Determinant of Matrix B:", determinant(B))

Determinant of Matrix A: -2
Determinant of Matrix B: 3362


The classical adjoint, or just adjoint, of a matrix has elements defined as by the formula:

$$ (\text{adj}(A))_{ij} = (-1)^{i+j} \det(A_{\backslash j,\backslash i}) $$

This can be used to compute the inverse of a matrix. The inverse of a matrix is defined as:

$$ \text{A}^{-1} = \frac{1}{\det(\text{A})} \text{adj}(\text{A}) $$

In [51]:
def adjoint(mat):
    n = len(mat)
    adj = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            sub_mat = np.delete(mat, j, axis=0)       # delete the j-th row
            sub_mat = np.delete(sub_mat, i, axis=1)   # delete the i-th column
            sign = (-1)**(i+j)
            adj[i][j] = sign * determinant(sub_mat)
    return adj

print("Inverse of Matrix A:\n", np.linalg.inv(A))
print("Inverse of Matrix B:\n", np.linalg.inv(B))

print(f'Inverse A:\n{adjoint(A)/determinant(A)}')
print(f'Inverse B:\n{adjoint(B)/determinant(B)}')

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of Matrix B:
 [[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]
Inverse A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Inverse B:
[[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]
