In [31]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,2],[3,4]])
B = np.array([[5,6,7],[7,80,9],[9,10,22]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[ 5  6  7]
 [ 7 80  9]
 [ 9 10 22]]


In [32]:
# determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)
# inverse of A
inv_A = np.linalg.inv(A)
print("\nInverse of Matrix A:\n", inv_A)

# determinant of B
det_B = np.linalg.det(B)
print("\nDeterminant of Matrix B:", det_B)
# inverse of B
inv_B = np.linalg.inv(B)
print("\nInverse of Matrix B:\n", inv_B)


Determinant of Matrix A: -2.0000000000000004

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix B: 3362.0000000000014

Inverse of Matrix B:
 [[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]


In [33]:
det_A = A[0,0]*A[1,1] - A[0,1]*A[1,0]
print("Determinant of Matrix A:", det_A)

det_B = B[0,0]*B[1,1]*B[2,2] + B[0,1]*B[1,2]*B[2,0] + B[0,2]*B[1,0]*B[2,1] - B[0,0]*B[1,2]*B[2,1] - B[0,1]*B[1,0]*B[2,2] - B[0,2]*B[1,1]*B[2,0]
print(f"Determinant of Matrix B: {det_B}")
print(f'{B[0,0]*B[1,1]*B[2,2]=}\n{B[0,1]*B[1,2]*B[2,0]=}\n{B[0,2]*B[1,0]*B[2,1]=}\n{B[0,0]*B[1,2]*B[2,1]=}\n{B[0,1]*B[1,0]*B[2,2]=}\n{B[0,2]*B[1,1]*B[2,0]=}')

Determinant of Matrix A: -2
Determinant of Matrix B: 3362
B[0,0]*B[1,1]*B[2,2]=8800
B[0,1]*B[1,2]*B[2,0]=486
B[0,2]*B[1,0]*B[2,1]=490
B[0,0]*B[1,2]*B[2,1]=450
B[0,1]*B[1,0]*B[2,2]=924
B[0,2]*B[1,1]*B[2,0]=5040


Calculating the determinant of a matrix using the formulae (where $A_{\backslash i,\backslash j}$ means the matrix with row i and column j removed):

$$ \begin{align}
|A| &= \sum_{i=1}^{n} (-1)^{i+j} a_{ij} |A_{\backslash i,\backslash j}| \\
    &= \sum_{j=1}^{n} (-1)^{i+j} a_{ij} |A_{\backslash i,\backslash j}|
\end{align} $$

In [37]:
def determinant(mat):
    n = len(mat)
    if n == 1:
        return mat[0][0]
    else:
        det = 0
        i = 0
        j = 0
        for i in range(n): # this works whether on each row (i) or each column (j)
            sub_mat = np.delete(mat, i, axis=0)       # delete the i-th row
            sub_mat = np.delete(sub_mat, j, axis=1)   # delete the j-th column
            sign = (-1)**(i+j)
            det += sign * mat[i][j] * determinant(sub_mat)
        return det
    
print("Determinant of Matrix A:", determinant(A))
print("Determinant of Matrix B:", determinant(B))

Determinant of Matrix A: -2
Determinant of Matrix B: 3362


The classical adjoint, or just adjoint, of a matrix has elements defined as by the formula:

$$ (\text{adj}(A))_{ij} = (-1)^{i+j} \det(A_{\backslash j,\backslash i}) $$

This can be used to compute the inverse of a matrix. The inverse of a matrix is defined as:

$$ \text{A}^{-1} = \frac{1}{\det(\text{A})} \text{adj}(\text{A}) $$

In [51]:
def adjoint(mat):
    n = len(mat)
    adj = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            sub_mat = np.delete(mat, j, axis=0)       # delete the j-th row
            sub_mat = np.delete(sub_mat, i, axis=1)   # delete the i-th column
            sign = (-1)**(i+j)
            adj[i][j] = sign * determinant(sub_mat)
    return adj

print("Inverse of Matrix A:\n", np.linalg.inv(A))
print("Inverse of Matrix B:\n", np.linalg.inv(B))

print(f'Inverse A:\n{adjoint(A)/determinant(A)}')
print(f'Inverse B:\n{adjoint(B)/determinant(B)}')

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of Matrix B:
 [[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]
Inverse A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Inverse B:
[[ 0.49672814 -0.0184414  -0.15050565]
 [-0.02171327  0.01397977  0.00118977]
 [-0.1933373   0.00118977  0.10648424]]


In [65]:
gram = A.T @ A
print(f'{A.T} \n @ \n{A} \n = \n{gram}')

[[1 3]
 [2 4]] 
 @ 
[[1 2]
 [3 4]] 
 = 
[[10 14]
 [14 20]]


Eigenvalues $\lambda$ satisfy the following equation:

$$ \det(\lambda I - A) = 0 $$

Alternatively, this can also be written as:

$$ \det(A - \lambda I) = 0 $$


$\lambda I - A$ is a square matrix with $n$ rows and $n$ columns.

$$ \lambda I - A = \begin{pmatrix} \lambda - A_{1,1} & -A_{1,2} & -A_{1,3} \\ -A_{2,1} & \lambda - A_{2,2} & -A_{2,3} \\ -A_{3,1} & -A_{3,2} & \lambda - A_{3,3} \end{pmatrix} $$

$$ |A| = \sum_{i=1}^{n} (-1)^{i+j} a_{ij} |A_{\backslash i,\backslash j}| $$

Eigenvalues and eigenvectors satisfy the following equation:

$$ Ax = \lambda x $$

where $x$ is a non-zero vector called an eigenvector.


In [185]:
# eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:\n", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

# compute the determinant of A - lambda I and lambda I - A
lambda_val = eigenvalues[0]  # choose any eigenvalue for demonstration
det_lambdaI_minus_A = np.linalg.det(lambda_val * np.eye(2) - A)
det_A_minus_lambdaI = np.linalg.det(A - lambda_val * np.eye(2))

print()
print(f'|A - λI|={det_A_minus_lambdaI}')
print(f'|λI - A|={det_lambdaI_minus_A}')

# AX = XΛ, where X is a matrix of eigenvectors in each column and Λ is the diagonal matrix of eigenvalues
print('\n -- AX = XΛ --')
print(f'{A@eigenvectors=}')
print(f'{eigenvectors @ np.diag(eigenvalues)=}')

# Ax = λx, where x is an eigenvector of A and λ is the corresponding eigenvalue
print('\n -- Ax = λx --')
print(f'{A @ eigenvectors.T[0]=}')
print(f'{eigenvectors.T[0]*eigenvalues[0]=}')

print('\n -- trA == Σλ --')
print(f'{A.trace()=}')
print(f'{sum(eigenvalues)=}')

print('\n -- |B| == Πλ --')
print(f'{np.linalg.det(A)=}')
print(f'{np.prod(eigenvalues)=}')

Eigenvalues of A:
 [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

|A - λI|=-1.250741480074576e-16
|λI - A|=-1.250741480074576e-16

 -- AX = XΛ --
A@eigenvectors=array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])
eigenvectors @ np.diag(eigenvalues)=array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

 -- Ax = λx --
A @ eigenvectors.T[0]=array([ 0.30697009, -0.21062466])
eigenvectors.T[0]*eigenvalues[0]=array([ 0.30697009, -0.21062466])

 -- trA == Σλ --
A.trace()=5
sum(eigenvalues)=5.0

 -- |B| == Πλ --
np.linalg.det(A)=-2.0000000000000004
np.prod(eigenvalues)=-1.9999999999999998


In [183]:
# eigenvalues and eigenvectors of B
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print("Eigenvalues of B:\n", eigenvalues_B)
print("Eigenvectors of B:\n", eigenvectors_B)

# compute the determinant of B - lambda I and lambda I - B
lambda_val = eigenvalues_B[0]  # choose any eigenvalue for demonstration
det_lambdaI_minus_B = np.linalg.det(lambda_val * np.eye(len(B)) - B)
det_B_minus_lambdaI = np.linalg.det(B - lambda_val * np.eye(len(B)))

print()
print(f'|B - λI|={det_B_minus_lambdaI}')
print(f'|λI - B|={det_lambdaI_minus_B}')

# BX = XΛ, where X is a matrix of eigenvectors in each column and Λ is the diagonal matrix of eigenvalues
print('\n -- BX = XΛ --')
print(f'{B@eigenvectors_B=}')
print(f'{eigenvectors_B @ np.diag(eigenvalues_B)=}')

# Bx = λx, where x is an eigenvector of B and λ is the corresponding eigenvalue
print('\n -- Bx = λx --')
print(f'{B @ eigenvectors_B.T[0]=}')
print(f'{eigenvectors_B.T[0]*eigenvalues_B[0]=}')

print('\n -- trB == Σλ --')
print(f'{B.trace()=}')
print(f'{sum(eigenvalues_B)=}')

print('\n -- |B| == Πλ --')
print(f'{np.linalg.det(B)=}')
print(f'{np.prod(eigenvalues_B)=}')

Eigenvalues of B:
 [82.27693518  1.78110307 22.94196175]
Eigenvectors of B:
 [[-0.09206393 -0.91967128  0.30301203]
 [-0.980016    0.03732471 -0.1846442 ]
 [-0.17633171  0.39091126  0.93492793]]

|B - λI|=-2.8073291467676186e-11
|λI - B|=2.8073291467676186e-11

 -- BX = XΛ --
B@eigenvectors_B=array([[-7.57473763e+00, -1.63802933e+00,  6.95169048e+00],
       [-8.06327129e+01,  6.64791552e-02, -4.23610007e+00],
       [-1.45080330e+01,  6.96253237e-01,  2.14490807e+01]])
eigenvectors_B @ np.diag(eigenvalues_B)=array([[-7.57473763e+00, -1.63802933e+00,  6.95169048e+00],
       [-8.06327129e+01,  6.64791552e-02, -4.23610007e+00],
       [-1.45080330e+01,  6.96253237e-01,  2.14490807e+01]])

 -- Bx = λx --
B @ eigenvectors_B.T[0]=array([ -7.57473763, -80.6327129 , -14.50803305])
eigenvectors_B.T[0]*eigenvalues_B[0]=array([ -7.57473763, -80.6327129 , -14.50803305])

 -- trB == Σλ --
B.trace()=107
sum(eigenvalues_B)=107.00000000000001

 -- |B| == Πλ --
np.linalg.det(B)=3362.0000000000014
np.

$$ A = X \Lambda X^{-1} $$

In [187]:
print(A)
print(eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors))

print(B)
print(eigenvectors_B @ np.diag(eigenvalues_B) @ np.linalg.inv(eigenvectors_B))

[[1 2]
 [3 4]]
[[1. 2.]
 [3. 4.]]
[[ 5  6  7]
 [ 7 80  9]
 [ 9 10 22]]
[[ 5.  6.  7.]
 [ 7. 80.  9.]
 [ 9. 10. 22.]]


$ \nabla_x f(Ax) = \begin{bmatrix} \frac{\partial_x f(Ax)}{\partial_{x_1}} \\ \frac{\partial_x f(Ax)}{\partial_{x_2}} \\ \vdots \\ \frac{\partial_x f(Ax)}{\partial_{x_n}} \end{bmatrix} $

$ (Ax)_{i} = \sum_{j=1}^n \sum_{i=1}^n A_{ji} x_i = \sum_{i=1}^n a_j x_i = a_j x $

$ \frac{\partial_x f(Ax)}{\partial_{x_i}} = a_j $

$a_j$ is the column vector of $A$. Therefore,

$ \nabla_x f(Ax) = A $

In [193]:
def matrix_vector_product(A, x):
    return np.dot(A, x)

def matrix_vector_product_basic(A, x):
    result = np.zeros_like(x)
    for i in range(len(x)):
        for j in range(len(x)):
            print(f'A[{i}][{j}] * x[{j}] = {A[i][j]} * {x[j]}')
            result[i] += A[i][j] * x[j]
    return result

A1 = np.array([[1, 2], [3, 4]])
x1 = np.array([5, 6])

print(matrix_vector_product(A1, x1))
print(matrix_vector_product_basic(A1, x1))

[17 39]
A[0][0] * x[0] = 1 * 5
A[0][1] * x[1] = 2 * 6
A[1][0] * x[0] = 3 * 5
A[1][1] * x[1] = 4 * 6
[17 39]
